### PR TITLE
fix python-index not added to credentials-metadata

### LINKED ISSUE #196: Authentication failure in running dependabot update on private-repo having pip as package-manager
Hey!

I am facing a  **_private_source_authentication_failure_** when trying to run dependabot-cli on private repo. I was trying to run dependabot update command. We authenticate with **username** and **password** and used an **AWS codeartifact repo** as source.

### Dependabot update command
```bash
dependabot update -f test.yaml
```

### Error 
```bash
........
........
updater | 2023/11/13 18:24:56 INFO Checking if boto3 1.24.84 needs updating
{"data":{"error-type":"private_source_authentication_failure","error-details":{"source":"https://example.com/"}},"type":"record_update_job_error"}
  proxy | 2023/11/13 18:24:56 [008] POST http://host.docker.internal:45341/update_jobs/cli/record_update_job_error
  proxy | 2023/11/13 18:24:56 [008] 200 http://host.docker.internal:45341/update_jobs/cli/record_update_job_error
updater | 2023/11/13 18:24:56 INFO Handled error whilst updating boto3: private_source_authentication_failure {:source=>"https:/example.com/"}
updater | 2023/11/13 18:24:56 INFO Checking if marshmallow 3.18.0 needs updating
  proxy | 2023/11/13 18:24:56 [009] POST http://host.docker.internal:45341/update_jobs/cli/record_update_job_error
{"data":{"error-type":"private_source_authentication_failure","error-details":{"source":"https://example.com/"}},"type":"record_update_job_error"}
.........
........
``` 
image

### Sample Job Description 

```yaml
job:
    package-manager: pip
    allowed-updates:
      - update-type: all
    security-advisories:
      - dependency-name: black
        affected-versions:
          - <20.0.0
        patched-versions: []
        unaffected-versions: []
    source:
        provider: github
        repo: example/test
        directory: /      
credentials:
  - type: python-index
    registry: [registry_url]
    token: [token]
```
_`What we are really looking for is to authenticate using username/password and using AWS codeartifact repo as source.`_

### PR DESCRIPTION
**Pull request by jakecoffman**
fix #196

When using a job definition containing credentials for a python index, the Dependabot CLI was not correctly updating the credentials metadata which is passed to the Updater. 

To fix this I flipped the logic to exclude `token` and `password` during the metadata population routine, which should also fix any others that we might have missed or any that are added in the future.

### CODE REVIEW

**Review by landongrindheim — APPROVED** [review]

File: cmd/dependabot/internal/cmd/update.go [hunk 1]
```diff
@@ -363,20 +363,12 @@ func processInput(input *model.Input, flags *UpdateFlags) {
...
-			}
-			if credential["registry"] != nil {
-				entry["registry"] = credential["registry"]
-			}
-			if credential["replaces-base"] != nil {
-				entry["replaces-base"] = credential["replaces-base"]
+			entry := make(map[string]any)
+			for k, v := range credential {
+				// Updater does not get credentials.
+				if k != "token" && k != "password" {
```
Comment (mctofu) [inline cmd/dependabot/internal/cmd/update.go:369]: Hex org & repos have some additional keys: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#hex-organization
