### PR TITLE
fix credential access check to work with GHES

### LINKED ISSUE #153: Is it possible to run the cli for git enterprise?
based on this issue https://github.com/dependabot/cli/issues/134 i tried to change the default host of git because i have a github enterprise instance, but didnt work. received a 401, althought couldnt get more info regarding to where is trying to get access to, if my instance or the github default.

Using the `--debug` didnt provide more info

```
{
  "job": {
    "package-manager": "npm_and_yarn",
    "allowed-updates": [
      {
        "update-type": "all"
      }
    ],
    "source": {
      "provider": "github",
      "repo": "demo-repo",
      "directory": "\/",
      "branch": "develop"
    }
  },
  "credentials": [
    {
      "type": "git_source",
      "host": "my_instance",
      "username": "x-access-token",
      "password": "my_token"
    },
    {
      "type": "npm_registry",
      "registry": "my_registry",
      "token": "my_token"
    }
  ]
}
```

Am i doing something wrong or is really not possible to access a different instance other than github.com ?

### PR DESCRIPTION
**Pull request by jakecoffman**
fix #153

The credential write access check was hardcoded to use api.github.com but that prevents it from working with GItHub Enterprise. 

This change uses the API endpoint defined in the input file if it's present, otherwise falls back to api.github.com.

### CODE REVIEW

File: internal/infra/run.go [hunk 1]
```diff
@@ -190,7 +190,11 @@ func checkCredAccess(ctx context.Context, creds []model.Credential) error {
 		if !strings.HasPrefix(credential, "ghp_") {
 			continue
 		}
-		r, err := http.NewRequestWithContext(ctx, "GET", authEndpoint, http.NoBody)
+		apiEndpoint := defaultApiEndpoint
+		if job != nil && job.Source.APIEndpoint != nil && *job.Source.APIEndpoint != "" {
+			apiEndpoint = *job.Source.APIEndpoint
+		}
+		r, err := http.NewRequestWithContext(ctx, "GET", apiEndpoint, http.NoBody)
```
Comment (brrygrdn) [inline internal/infra/run.go:197]: 👍🏻

**Review by brrygrdn — APPROVED** [review]

**Comment by jakecoffman** [comment]
I booted a GHES instance and verified this works.
